---
title: "Getting RDS Data"
author: "Vincent Liu"
date: "`r lubridate::today()`"
output: html_document
---

```{r, setup, include=FALSE}
library(tidyverse)
library(httr)
library(DT)
library(urbnthemes)
library(plotly)

set_urbn_defaults()


#path = "../../Data/"
```


### PC19 by Category Table

```{r}
pc19_category <- read_csv(paste0(path, "Output_Data/", "PC2019_by_category.csv")) %>%
  select(!1) 
pc19_catgeory_num <- read_csv(paste0(path, "Output_Data/", "PC2019_by_category.csv")) %>%
  select(!c(1,3, 9:13)) 
pc19_catgeory_perc <- read_csv(paste0(path, "Output_Data/", "PC2019_by_category.csv")) %>%
  select(!c(1,3:8)) 

saveRDS(pc19_category, "pc19_category.rds")
saveRDS(pc19_catgeory_num, "pc19_category_number.rds")
saveRDS(pc19_catgeory_perc, "pc19_category_percent.rds")

```

### NPO Trend Chart
```{r, warning =FALSE}
source(paste0("../../", "Functions","/Process_BMF_file.R"))

bmf2022 <- process_bmf(2022,01) %>% add_column(YEAR = "2022", .after="EIN")
# lack bmf2021
bmf2020 <-process_bmf(2020,04) %>% add_column(YEAR = "2020", .after="EIN")
bmf2019 <- process_bmf(2010,08) %>% add_column(YEAR = "2019", .after="EIN")
bmf2018 <- process_bmf(2018,12) %>% add_column(YAER = "2018", .after="EIN")
bmf2017 <- process_bmf(2017,09) %>% add_column(YAER = "2017", .after="EIN")       # for years that have multiple BMFs, I picked the earlier one 
bmf2016 <- process_bmf(2016,02) %>% add_column(YEAR = "2016", .after="EIN")

bmf2015 <- process_bmf(2015,02) %>% add_column(YEAR = "2015", .after="EIN")
bmf2014 <- process_bmf(2014,02) %>% add_column(YEAR = "2014", .after="EIN")
bmf2013 <- process_bmf(2013,02) %>% add_column(YEAR = "2013", .after="EIN")
bmf2012 <- process_bmf(2012,02) %>% add_column(YEAR = "2012", .after="EIN")
bmf2011 <- process_bmf(2011,06) %>% add_column(YEAR = "2011", .after="EIN")
bmf2010 <- process_bmf(2010,01) %>% add_column(YEAR = "2010", .after="EIN")

bmf2009 <- process_bmf(2009,01) %>% add_column(Year = "2009", .after="EIN")
bmf2008 <- process_bmf(2008,01) %>% add_column(Year = "2008", .after="EIN") #No Outnccs information
# bmf2008 <- bmf2008 %>% add_column(OUTNCCS = rep("IN", nrow(bmf2008)))
bmf2007 <- process_bmf(2007,01) %>% add_column(Year = "2007", .after="EIN")
bmf2006 <- process_bmf(2006,01) %>% add_column(Year = "2006", .after="EIN")
bmf2005 <- process_bmf(2005,07) %>% add_column(Year = "2005", .after="EIN")

bmf2004 <- process_bmf(2004,04) %>% add_column(Year = "2004", .after="EIN")
bmf2003 <- process_bmf(2003,01) %>% add_column(Year = "2003", .after="EIN")
bmf2002 <- process_bmf(2002,07) %>% add_column(Year = "2002", .after="EIN") #change month to # 07 (in 0201, EIN column is documented as ein) 
bmf2001 <- process_bmf(2001,07) %>% add_column(Year = "2001", .after="EIN")
bmf2000 <- process_bmf(2000,05) %>% add_column(Year = "2000", .after="EIN")

bmf1999 <- process_bmf(1999,12) %>% add_column(Year = "1999", .after="EIN")
bmf1998 <- process_bmf(1998,09) %>% add_column(Year = "1998", .after="EIN")
bmf1997 <- process_bmf(1997,10) %>% add_column(Year = "1997", .after="EIN")
bmf1996 <- process_bmf(1996,06) %>% add_column(Year = "1996", .after="EIN")
bmf1995 <- process_bmf(1995,08) %>% add_column(Year = "1995", .after="EIN")

bmf1989 <- process_bmf(1989, 01) %>% add_column(Year = "1989", .after="EIN")

```

```{r}
source(paste0("../../", "Functions","/Get_nonprofit_size.R"))
size22 <- get_size(2022)
size20 <- get_size(2020)
size19 <- get_size(2019)
size18 <- get_size(2018)
size17 <- get_size(2017)
size16 <- get_size(2016)
size15 <- get_size(2015)

size14 <- get_size(2014)
size13 <- get_size(2013)
size12 <- get_size(2012)
size11 <- get_size(2011)
size10 <- get_size(2010)

size09 <- get_size(2009)
size08 <- get_size(2008)
size07 <- get_size(2007)
size06 <- get_size(2006)
size05 <- get_size(2005)

size04 <- get_size(2004)
size03 <- get_size(2003)
size02 <- get_size(2002)
size01 <- get_size(2001)
size00 <- get_size(2000)

size99 <- get_size(1999)
size98 <- get_size(1998)
size97 <- get_size(1997)
size96 <- get_size(1996) 
size95 <- get_size(1995)

size89 <- get_size(1989)
  
size <- rbind(size22, size20,
              size19, size18, size17, size16, size15, 
              size14, size13, size12, size11, size10, 
              size09, size08, size07, size06, size05, 
              size04, size03, size02, size01, size00,
              size99, size98, size97, size96, size95,
              size89) 

size <- size %>%
  mutate(
    `Public Charity (%)` = round(
      `501(c)(3) public charities`/`All registered nonprofits`, 4)
    *100) %>%
  mutate(
    `Private Foundation (%)` = round(
      `501(c)(3) private foundations`/`All registered nonprofits`, 4
      )*100)
```


```{r}
saveRDS(size, "nonprofit_size_table.rds")
size <- readRDS("nonprofit_size_table.rds")

size 
```

```{r}
source(paste0("../../", "Functions","/Get_trend_chart.R"))
source(paste0("../../", "Functions","/Get_trend_chart_perc.R"))


nonprofit_trend_perc(size, c(2000, 2008, 2019, 1989, 2020))
```



```{r}
plotly::ggplotly( 
  size %>%
 #   filter(Year %in% c(1989, 2022, 2020, 2012, 2002)) %>%
    select(!5:6) %>% # Number !5:6, Perc !2:4 
    pivot_longer(2:4, names_to = "Type", values_to = "Count") %>%
    mutate(Year = as.numeric(Year)) %>%
    ggplot(aes(x = Year, y= Count,  
               color=Type, 
               group=Type)) +
    geom_line(size=1.5) +
    geom_point(size = 2) +
    labs(x= NULL, y= NULL) +
    ggtitle("A Trend on Number of 501c(3) Nonprofits") +
    scale_x_continuous(expand = c(0,0),
                       limits = c(1989, 2022),
                       breaks = c(seq(1989,2022,1))) +
    scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1600000), 
                     breaks = c(0, 100000, seq(500000, 1500000, 500000))) +
    theme(axis.line.y = element_blank(),
          axis.ticks = element_blank()) +
   # theme(legend.position = "bottom")
     theme(legend.position="right", 
           legend.direction = "vertical")
)  %>% 
  layout(legend = list(orientation = "h",
                       x = 0.015, 
                       y = -0.15
                       ), 
         hoverlabel = list(bgcolor = "white")
        )
```


```{r}
plotly::ggplotly(
  size %>%
    filter(Year %in% c(2022, 2020, 2012, 2002)) %>%
    select(!2:4) %>% # Number !5:6, Perc !2:4 
    pivot_longer(2:3, names_to = "Type", values_to = "Percent (%)") %>%
    
    ggplot(aes(x = Year, y= `Percent (%)`, 
               color=Type, 
               group=Type)) +
    geom_line(size=1.5) +
    geom_point(size = 2) +
    ggtitle("A Trend on PC and PF Divide (%)") +
    labs(x= NULL, y = NULL) +
    scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 85), 
                     breaks = c(0, 5, 10, seq(50,80,10))) +
    theme(axis.line.y = element_blank(),
          axis.ticks = element_blank()) + 
   # theme(legend.position = "bottom")
     theme(legend.position="right", 
           legend.direction = "vertical")
) %>% 
  layout(legend = list(orientation = "h",
                       x = 0.2, 
                       y = -0.15), 
         hoverlabel = list(bgcolor = "white"))


```


```{r}
source("../../Functions/Process_core_file.R")
list.files(path = "../../Functions/")
```


```{r}
size <- readRDS("nonprofit_size_table.rds")
DT::datatable(size)
```


*** Note: Year should be numeric


```{r}
npo_size22 <- bmf2022 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2022") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size20 <- bmf2020 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2020") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size19 <- bmf2019 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2019") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size18 <- bmf2018 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2018") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size17 <- bmf2017 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2017") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size16 <- bmf2016 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2016") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size15 <- bmf2015 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2015") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size14 <- bmf2014 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2014") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size13 <- bmf2013 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2013") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size12 <- bmf2012 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2012") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size11 <- bmf2011 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2011") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 

npo_size10 <- bmf2010 %>% 
  group_by(STATE) %>% 
  summarise(COUNT = n()) %>% 
  mutate(Year = "2010") %>%
  right_join(usmap::statepop %>% 
               select(abbr, full), 
             by = c("STATE" = "abbr")) %>% 
  rename(STATE_NAME=full) %>%
  relocate(STATE_NAME, .after = STATE) 
```

```{r}
all_npo_size <- rbind(npo_size22,
                      npo_size20, npo_size19, npo_size18, npo_size17, npo_size16,
                      npo_size15, npo_size14, npo_size13, npo_size12, npo_size11,
                      npo_size10)

saveRDS(all_npo_size, "nonprofit_size_by_state.rds")
```

```{r}
usa_states <- geojsonio::geojson_read("https://rstudio.github.io/leaflet/json/us-states.geojson", what = "sp")

size_by_state <- tigris::geo_join(usa_states, all_npo_size, "name","STATE_NAME") 

all_npo_size %>% filter(Year %in% c("2022", "2020", "2010")) %>% group_by(STATE) %>% summarise(Count = sum(COUNT)) %>% ungroup() %>% mutate(STATE_NAME = STATE_NAME)
```

```{r}
source("../../Functions/Get_size_map.R")

create_size_map(all_npo_size, c("2022", "2020", "2010"))
```


```{r}
size_map
```



