---
title: "R Markdown file to get data for the PF page of Shiny and make sure functions are working"
author: "Vincent Liu"
date: "`r Sys.Date()`"
output: pdf_document
---

## Initial Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      eval = TRUE,
                      warning = FALSE)

library(tidyverse)
library(httr)
library(DT)
library(urbnthemes)
library(plotly)

set_urbn_defaults()

source("../../Functions/Process_core_file.R")
source("../../Functions/Get_finance_data.R")
source("../../Functions/PF_finance.R")
```


## Re-clean PF 2019 Data
```{r}
pf2019 <- read_csv("../../Data/coreco.core2019pf.csv", col_types = cols_only(
                EIN = col_character(), 
                OUTNCCS = col_character(),  # Outside NCCS Scope?
                SUBSECCD = col_character(), # Subsection Code
                FNDNCD = col_character(), # Reason for 501(c)(3) status
                NTMAJ12 = col_character(), # 
                P1TOTREV = col_double(), #Total Revenue Per book
                P1TOTEXP = col_double(),  # Total Expenditure Per book
                P2TOTAST = col_double(), 
                LEVEL1 = col_character(),  
                NAME = col_character(),
                CITY = col_character(),
                STATE = col_character(),
                ZIP5 = col_character(),
                MSA_NECH = col_character(),
                PMSA = col_character(),
                LONGITUDE = col_double(),
                LATITUDE = col_double()))

pf2019 <- pf2019 %>%
    left_join(nteedocalleins, by = "EIN") 

  firlet = str_sub(pf2019$NTEEFINAL, 1, 1)
  fir2let = str_sub(pf2019$NTEEFINAL, 1, 2)
  fir3let = str_sub(pf2019$NTEEFINAL, 1, 3)
  
  pf2019_cleaned <- pf2019 %>%
    mutate(NTEEGRP = "  ") %>%
    mutate(NTEEGRP = case_when(
      firlet %in% arts ~ "Arts",
      firlet %in% othered & !(fir2let %in% highered)  ~ "Other education",
      fir2let %in% highered  ~ "Higher education",
      firlet %in% envanimals ~ "Environment and animals",
      firlet %in% otherhlth & !(fir3let %in% hospitals) ~ "Other health care",
      fir3let %in% hospitals ~ "Hospitals and primary care facilities",
      firlet %in% humanserv ~ "Human services",
      firlet %in% intl ~ "International",
      firlet %in% pubben ~ "Other public and social benefit",
      firlet %in% relig ~ "Religion related")) %>%
    mutate(NTEEGRP = if_else(is.na(NTEEFINAL), 
                             "Other public and social benefit", NTEEGRP)) %>%
    
      mutate(EXPCAT = "  ") %>%
      mutate(EXPCAT = case_when(
        P1TOTEXP < 100000 ~ "a. Under $100,000",
        P1TOTEXP >= 100000 & P1TOTEXP < 500000 ~ "b. $100,000 to $499,999",
        P1TOTEXP >= 500000 & P1TOTEXP < 1000000 ~ "c. $500,000 to $999,999",
        P1TOTEXP >= 1000000 & P1TOTEXP < 5000000 ~ "d. $1 million to $4.99 million",
        P1TOTEXP >= 5000000 & P1TOTEXP < 10000000 ~ "e. $5 million to $9.99 million",
        P1TOTEXP >= 10000000 ~ "f. $10 million or more"))
  
pf2019_cleaned %>% select(P1TOTREV, P1TOTEXP, P2TOTAST, NTEEGRP, EXPCAT, STATE, ZIP5)
  
write.csv("pf2019_cleaned", "../../Data/core2019pf.csv")
```


## Get PF data
```{r}
# PF lacks 2018, 2017, 2016 data
pf2019 <- get_pf_finance_data(2019)
#pf2018 <- get_pf_finance_data(2018)
#pf2017 <- get_pf_finance_data(2017)
#pf2016 <- get_pf_finance_data(2016)
pf2015 <- get_pf_finance_data(2015)
pf2014 <- get_pf_finance_data(2014)
pf2013 <- get_pf_finance_data(2013)
pf2012 <- get_pf_finance_data(2012)
pf2011 <- get_pf_finance_data(2011)
pf2010 <- get_pf_finance_data(2010)
pf2009 <- get_pf_finance_data(2009)
pf2008 <- get_pf_finance_data(2008)
pf2007 <- get_pf_finance_data(2007)

pf_finance <- rbind(pf2019, pf2015, pf2014, pf2013, pf2012,
                    pf2011, pf2010, pf2009, pf2008, pf2007)

saveRDS(pf_finance, "pf_finance.rds")
```


## Test functions
```{r}
## Try out functions 
read_csv(paste("https://nccs-data.urban.org/dl.php?f=core/",  
                   as.character(2018), "/coreco.core", as.character(2018),
                   tolower("PF"), ".csv", sep =""))

pf_category <- pf_finance_category(pf_finance, c("AZ", "CA", "IL", "MN", "DC"))
pf_exp <- pf_finance_expense(pf_finance, c("AZ", "CA", "IL", "MN", "DC"))

finance_chart_expense(pf_exp, pf_exp$"Number")
finance_chart_category(pf_category, pf_category$"Number")

```



